version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: code-analysis-mongodb
    ports:
      - "27018:27017"  # Map to port 27018 on host instead of default 27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=ai-sdlc--agent-poc
    restart: unless-stopped
    command: mongod --auth
    networks:
      - code-analysis-network

  # Initialize the database with Python
  mongo-init:
    build:
      context: .
      dockerfile: mongodb-init.Dockerfile
    container_name: mongo-init-python
    restart: "no"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    networks:
      - code-analysis-network

networks:
  code-analysis-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
